import {Injectable, signal} from '@angular/core';

@Injectable({
  providedIn: 'root'
})


export class LangService {


  phrases: Record<string, {[key:string]:string}> = {
  en: {
    HARVEST_POTENTIAL: 'Harvest Potential',
    SAVINGS: 'Savings',
    ROI: 'ROI',
    PAYBACK_PERIOD: 'Payback period',
    YEARS: 'Years',
    ANNUAL_RETURN: 'Annual return',
    PER_YEAR: 'Per year',
    FORECAST_16D: '16 day forecast',
    RWH_SYSTEM: 'Rain water harvesting system',
    COST: 'Cost',
    CAPACITY: 'Capacity',
    AGR_SYSTEM: 'Artificial ground replenishment system',
    UTIL_VS_HARVEST: 'Utilisation vs harvestable',
    ENV_IMPACT: 'Environmental impact',
    WATER_SAVED: 'Water saved',
    GROUNDWATER_SAVED: 'Ground water saved',
    ENERGY_SAVED: 'Energy saved',
    CO2_AVOIDED: 'CO₂ avoided',
    AQUIFER: 'Ground water aquifer',
    AQUIFER_INFO: 'Aquifer info',
    MONTHLY_FORECAST: 'Monthly forecast',
    LEADERBOARD: 'Leader board',
    DRAW_HELP: 'Single click to put down point, Double click to close polygon',
    DRAW_ROOF: 'Draw polygon around your roof',
    DRAW_SPACE: 'Please draw polygon around free space',
    ROOF_MATERIALS: 'Roof materials',
    WATER_BILL: 'What is your monthly water bill?',
    WATER_USAGE: 'Monthly household water usage',
    CONFIRM: 'Confirm',
    REDO: 'Redo'
  },
  hi: {
    HARVEST_POTENTIAL: 'कटाई की क्षमता',
    SAVINGS: 'बचत',
    ROI: 'आरओआई',
    PAYBACK_PERIOD: 'भुगतान अवधि',
    YEARS: 'साल',
    ANNUAL_RETURN: 'वार्षिक रिटर्न',
    PER_YEAR: 'प्रति वर्ष',
    FORECAST_16D: '16 दिन का पूर्वानुमान',
    RWH_SYSTEM: 'वर्षा जल संचयन प्रणाली',
    COST: 'लागत',
    CAPACITY: 'क्षमता',
    AGR_SYSTEM: 'कृत्रिम भूजल पुनर्भरण प्रणाली',
    UTIL_VS_HARVEST: 'उपयोग बनाम संचयन',
    ENV_IMPACT: 'पर्यावरणीय प्रभाव',
    WATER_SAVED: 'पानी की बचत',
    GROUNDWATER_SAVED: 'भूजल की बचत',
    ENERGY_SAVED: 'ऊर्जा की बचत',
    CO2_AVOIDED: 'CO₂ से बचाव',
    AQUIFER: 'भूजल भंडार',
    AQUIFER_INFO: 'भूजल भंडार की जानकारी',
    MONTHLY_FORECAST: 'मासिक पूर्वानुमान',
    LEADERBOARD: 'लीडर बोर्ड',
    DRAW_HELP: 'बिंदु रखने के लिए एक क्लिक करें, बहुभुज बंद करने के लिए डबल क्लिक करें',
    DRAW_ROOF: 'अपने छत के चारों ओर बहुभुज बनाएं',
    DRAW_SPACE: 'कृपया खाली स्थान के चारों ओर बहुभुज बनाएं',
    ROOF_MATERIALS: 'छत की सामग्री',
    WATER_BILL: 'आपका मासिक पानी का बिल कितना है?',
    WATER_USAGE: 'मासिक घरेलू पानी की खपत',
    CONFIRM: 'पुष्टि करें',
    REDO: 'पुनः करें'
  },
  ta: {
    HARVEST_POTENTIAL: 'அறுவடை திறன்',
    SAVINGS: 'சேமிப்பு',
    ROI: 'ROI',
    PAYBACK_PERIOD: 'திருப்பிச் செலுத்தும் காலம்',
    YEARS: 'ஆண்டுகள்',
    ANNUAL_RETURN: 'ஆண்டு வருமானம்',
    PER_YEAR: 'ஒரு ஆண்டுக்கு',
    FORECAST_16D: '16 நாள் முன்னறிவிப்பு',
    RWH_SYSTEM: 'மழை நீர் சேகரிப்பு அமைப்பு',
    COST: 'செலவு',
    CAPACITY: 'திறன்',
    AGR_SYSTEM: 'செயற்கை நிலத்தடி நீர் நிரப்பும் அமைப்பு',
    UTIL_VS_HARVEST: 'பயன்பாடு vs சேகரிக்கக்கூடியது',
    ENV_IMPACT: 'சுற்றுச்சூழல் தாக்கம்',
    WATER_SAVED: 'நீர் சேமிப்பு',
    GROUNDWATER_SAVED: 'நிலத்தடி நீர் சேமிப்பு',
    ENERGY_SAVED: 'ஆற்றல் சேமிப்பு',
    CO2_AVOIDED: 'CO₂ தவிர்க்கப்பட்டது',
    AQUIFER: 'நிலத்தடி நீர் அக்விபர்',
    AQUIFER_INFO: 'அக்விபர் தகவல்',
    MONTHLY_FORECAST: 'மாதாந்திர முன்னறிவிப்பு',
    LEADERBOARD: 'தலைவர் பலகை',
    DRAW_HELP: 'புள்ளியை வைக்க ஒருமுறை கிளிக் செய்யவும், பலகோணம் மூட இருமுறை கிளிக் செய்யவும்',
    DRAW_ROOF: 'உங்கள் கூரையின் சுற்றிலும் பலகோணம் வரையவும்',
    DRAW_SPACE: 'தயவுசெய்து காலியாக உள்ள இடத்தின் சுற்றிலும் பலகோணம் வரையவும்',
    ROOF_MATERIALS: 'கூரை பொருட்கள்',
    WATER_BILL: 'உங்கள் மாதாந்திர நீர் பில் என்ன?',
    WATER_USAGE: 'மாதாந்திர வீட்டு நீர் பயன்பாடு',
    CONFIRM: 'உறுதிப்படுத்தவும்',
    REDO: 'மீண்டும் செய்யவும்'
  },
  te: {
    HARVEST_POTENTIAL: 'పంట సామర్థ్యం',
    SAVINGS: 'మొత్తం పొదుపులు',
    ROI: 'ROI',
    PAYBACK_PERIOD: 'తిరిగి చెల్లింపు వ్యవధి',
    YEARS: 'సంవత్సరాలు',
    ANNUAL_RETURN: 'వార్షిక లాభం',
    PER_YEAR: 'ప్రతి సంవత్సరం',
    FORECAST_16D: '16 రోజుల అంచనా',
    RWH_SYSTEM: 'వర్షపు నీరు సంగ్రహణ వ్యవస్థ',
    COST: 'ఖర్చు',
    CAPACITY: 'సామర్థ్యం',
    AGR_SYSTEM: 'కృత్రిమ భూగర్భ జల పునఃనింపే వ్యవస్థ',
    UTIL_VS_HARVEST: 'ఉపయోగం vs సంగ్రహించదగినది',
    ENV_IMPACT: 'పర్యావరణ ప్రభావం',
    WATER_SAVED: 'నీటి పొదుపు',
    GROUNDWATER_SAVED: 'భూగర్భ జల పొదుపు',
    ENERGY_SAVED: 'శక్తి పొదుపు',
    CO2_AVOIDED: 'CO₂ నివారణ',
    AQUIFER: 'భూగర్భ జల భాండాగారం',
    AQUIFER_INFO: 'భాండాగారం సమాచారం',
    MONTHLY_FORECAST: 'మాసిక అంచనా',
    LEADERBOARD: 'లీడర్ బోర్డు',
    DRAW_HELP: 'పాయింట్ పెట్టడానికి ఒకసారి క్లిక్ చేయండి, పాలిగాన్ మూసివేయడానికి డబుల్ క్లిక్ చేయండి',
    DRAW_ROOF: 'మీ కప్పు చుట్టూ పాలిగాన్ గీయండి',
    DRAW_SPACE: 'ఖాళీ ప్రదేశం చుట్టూ పాలిగాన్ గీయండి',
    ROOF_MATERIALS: 'కప్పు పదార్థాలు',
    WATER_BILL: 'మీ నెలసరి నీటి బిల్లు ఎంత?',
    WATER_USAGE: 'నెలసరి గృహ నీటి వినియోగం',
    CONFIRM: 'నిర్ధారించండి',
    REDO: 'మళ్ళీ చేయండి'
  },
  bn: {
    HARVEST_POTENTIAL: 'ফসলের সম্ভাবনা',
    SAVINGS: 'সঞ্চয়',
    ROI: 'ROI',
    PAYBACK_PERIOD: 'ফেরত সময়কাল',
    YEARS: 'বছর',
    ANNUAL_RETURN: 'বার্ষিক রিটার্ন',
    PER_YEAR: 'প্রতি বছর',
    FORECAST_16D: '১৬ দিনের পূর্বাভাস',
    RWH_SYSTEM: 'বৃষ্টির জল সংগ্রহ ব্যবস্থা',
    COST: 'খরচ',
    CAPACITY: 'ক্ষমতা',
    AGR_SYSTEM: 'কৃত্রিম ভূগর্ভস্থ জল পুনঃপূরণ ব্যবস্থা',
    UTIL_VS_HARVEST: 'ব্যবহার বনাম সংগ্রহযোগ্য',
    ENV_IMPACT: 'পরিবেশগত প্রভাব',
    WATER_SAVED: 'জল সঞ্চয়',
    GROUNDWATER_SAVED: 'ভূগর্ভস্থ জলের সঞ্চয়',
    ENERGY_SAVED: 'শক্তি সঞ্চয়',
    CO2_AVOIDED: 'CO₂ এড়ানো হয়েছে',
    AQUIFER: 'ভূগর্ভস্থ জলাধার',
    AQUIFER_INFO: 'জলাধার তথ্য',
    MONTHLY_FORECAST: 'মাসিক পূর্বাভাস',
    LEADERBOARD: 'লিডার বোর্ড',
    DRAW_HELP: 'একটি বিন্দু রাখতে একবার ক্লিক করুন, বহুভুজ বন্ধ করতে ডাবল ক্লিক করুন',
    DRAW_ROOF: 'আপনার ছাদের চারপাশে বহুভুজ আঁকুন',
    DRAW_SPACE: 'অনুগ্রহ করে খালি জায়গার চারপাশে বহুভুজ আঁকুন',
    ROOF_MATERIALS: 'ছাদের উপকরণ',
    WATER_BILL: 'আপনার মাসিক জল বিল কত?',
    WATER_USAGE: 'মাসিক পরিবারের জল ব্যবহার',
    CONFIRM: 'নিশ্চিত করুন',
    REDO: 'পুনরায় করুন'
  },
  mr: {
    HARVEST_POTENTIAL: 'पीक क्षमता',
    SAVINGS: 'बचत',
    ROI: 'ROI',
    PAYBACK_PERIOD: 'परतफेड कालावधी',
    YEARS: 'वर्षे',
    ANNUAL_RETURN: 'वार्षिक परतावा',
    PER_YEAR: 'प्रति वर्ष',
    FORECAST_16D: '१६ दिवसांचा अंदाज',
    RWH_SYSTEM: 'पावसाचे पाणी साठवण प्रणाली',
    COST: 'खर्च',
    CAPACITY: 'क्षमता',
    AGR_SYSTEM: 'कृत्रिम भूजल पुनर्भरण प्रणाली',
    UTIL_VS_HARVEST: 'वापर विरुद्ध साठवण',
    ENV_IMPACT: 'पर्यावरणीय परिणाम',
    WATER_SAVED: 'पाण्याची बचत',
    GROUNDWATER_SAVED: 'भूजल बचत',
    ENERGY_SAVED: 'ऊर्जेची बचत',
    CO2_AVOIDED: 'CO₂ टाळले',
    AQUIFER: 'भूजल जलाशय',
    AQUIFER_INFO: 'जलाशय माहिती',
    MONTHLY_FORECAST: 'मासिक अंदाज',
    LEADERBOARD: 'लीडर बोर्ड',
    DRAW_HELP: 'बिंदू ठेवण्यासाठी एकदा क्लिक करा, बहुभुज बंद करण्यासाठी डबल क्लिक करा',
    DRAW_ROOF: 'तुमच्या छताभोवती बहुभुज काढा',
    DRAW_SPACE: 'कृपया मोकळ्या जागेभोवती बहुभुज काढा',
    ROOF_MATERIALS: 'छताचे साहित्य',
    WATER_BILL: 'तुमचे मासिक पाणी बिल किती आहे?',
    WATER_USAGE: 'मासिक घरगुती पाणी वापर',
    CONFIRM: 'निश्चित करा',
    REDO: 'पुन्हा करा'
  },
  gu: {
    HARVEST_POTENTIAL: 'કાપણી ક્ષમતા',
    SAVINGS: 'બચત',
    ROI: 'ROI',
    PAYBACK_PERIOD: 'પરત ચુકવણી સમયગાળો',
    YEARS: 'વર્ષ',
    ANNUAL_RETURN: 'વાર્ષિક વળતર',
    PER_YEAR: 'દર વર્ષે',
    FORECAST_16D: '16 દિવસનો અંદાજ',
    RWH_SYSTEM: 'વરસાદી પાણી સંગ્રહ પ્રણાલી',
    COST: 'ખર્ચ',
    CAPACITY: 'ક્ષમતા',
    AGR_SYSTEM: 'કૃત્રિમ ભૂગર્ભ જળ રિચાર્જ પ્રણાલી',
    UTIL_VS_HARVEST: 'ઉપયોગ વિરુદ્ધ સંગ્રહ',
    ENV_IMPACT: 'પર્યાવરણીય અસર',
    WATER_SAVED: 'પાણી બચ્યું',
    GROUNDWATER_SAVED: 'ભૂગર્ભ જળ બચ્યું',
    ENERGY_SAVED: 'ઊર્જા બચી',
    CO2_AVOIDED: 'CO₂ ટાળ્યું',
    AQUIFER: 'ભૂગર્ભ જળ સ્ત્રોત',
    AQUIFER_INFO: 'જળ સ્ત્રોત માહિતી',
    MONTHLY_FORECAST: 'માસિક અંદાજ',
    LEADERBOARD: 'લીડર બોર્ડ',
    DRAW_HELP: 'બિંદુ મૂકવા માટે એકવાર ક્લિક કરો, બહુકોણ બંધ કરવા માટે ડબલ ક્લિક કરો',
    DRAW_ROOF: 'તમારી છતની આસપાસ બહુકોણ દોરો',
    DRAW_SPACE: 'કૃપા કરીને ખાલી જગ્યાની આસપાસ બહુકોણ દોરો',
    ROOF_MATERIALS: 'છત સામગ્રી',
    WATER_BILL: 'તમારું માસિક પાણી બિલ કેટલું છે?',
    WATER_USAGE: 'માસિક ઘરેલુ પાણીનો ઉપયોગ',
    CONFIRM: 'પુષ્ટિ કરો',
    REDO: 'ફરીથી કરો'
  },
  kn: {
    HARVEST_POTENTIAL: 'ಹಣಿಕೆ ಸಾಮರ್ಥ್ಯ',
    SAVINGS: 'ಉಳಿತಾಯ',
    ROI: 'ROI',
    PAYBACK_PERIOD: 'ಹಿಂತಿರುಗಿಸುವ ಅವಧಿ',
    YEARS: 'ವರ್ಷಗಳು',
    ANNUAL_RETURN: 'ವಾರ್ಷಿಕ ಆದಾಯ',
    PER_YEAR: 'ಪ್ರತಿ ವರ್ಷ',
    FORECAST_16D: '16 ದಿನಗಳ ಮುನ್ಸೂಚನೆ',
    RWH_SYSTEM: 'ಮಳೆ ನೀರು ಸಂಗ್ರಹಣಾ ವ್ಯವಸ್ಥೆ',
    COST: 'ವೆಚ್ಚ',
    CAPACITY: 'ಸಾಮರ್ಥ್ಯ',
    AGR_SYSTEM: 'ಕೃತಕ ಭೂಗರ್ಭ ಜಲ ತುಂಬಿಸುವ ವ್ಯವಸ್ಥೆ',
    UTIL_VS_HARVEST: 'ಬಳಕೆ vs ಸಂಗ್ರಹಿಸಬಹುದಾದ',
    ENV_IMPACT: 'ಪರಿಸರದ ಪರಿಣಾಮ',
    WATER_SAVED: 'ನೀರು ಉಳಿಸಲಾಗಿದೆ',
    GROUNDWATER_SAVED: 'ಭೂಗರ್ಭಜಲ ಉಳಿಸಲಾಗಿದೆ',
    ENERGY_SAVED: 'ಶಕ್ತಿ ಉಳಿಸಲಾಗಿದೆ',
    CO2_AVOIDED: 'CO₂ ತಪ್ಪಿಸಲಾಗಿದೆ',
    AQUIFER: 'ಭೂಗರ್ಭಜಲ ಆಕ್ವಿಫರ್',
    AQUIFER_INFO: 'ಆಕ್ವಿಫರ್ ಮಾಹಿತಿ',
    MONTHLY_FORECAST: 'ಮಾಸಿಕ ಮುನ್ಸೂಚನೆ',
    LEADERBOARD: 'ಲೀಡರ್ ಬೋರ್ಡ್',
    DRAW_HELP: 'ಬಿಂದು ಇಡಲು ಒಮ್ಮೆ ಕ್ಲಿಕ್ ಮಾಡಿ, ಬಹುಭುಜ ಮುಚ್ಚಲು ಡಬಲ್ ಕ್ಲಿಕ್ ಮಾಡಿ',
    DRAW_ROOF: 'ನಿಮ್ಮ ಮನೆಯ ಮೇಲ್ಚಾವಣಿಯ ಸುತ್ತ ಬಹುಭುಜ ಚಿತ್ರಿಸಿ',
    DRAW_SPACE: 'ದಯವಿಟ್ಟು ಖಾಲಿ ಜಾಗದ ಸುತ್ತ ಬಹುಭುಜ ಚಿತ್ರಿಸಿ',
    ROOF_MATERIALS: 'ಮೇಲ್ಚಾವಣಿ ವಸ್ತುಗಳು',
    WATER_BILL: 'ನಿಮ್ಮ ಮಾಸಿಕ ನೀರಿನ ಬಿಲ್ ಎಷ್ಟು?',
    WATER_USAGE: 'ಮಾಸಿಕ ಗೃಹ ನೀರಿನ ಬಳಕೆ',
    CONFIRM: 'ದೃಢೀಕರಿಸಿ',
    REDO: 'ಮತ್ತೆ ಮಾಡಿ'
  },
  ml: {
    HARVEST_POTENTIAL: 'വിളവെടുപ്പ് ശേഷി',
    SAVINGS: 'സംഭരണം',
    ROI: 'ROI',
    PAYBACK_PERIOD: 'തിരിച്ചടവ് കാലാവധി',
    YEARS: 'വർഷങ്ങൾ',
    ANNUAL_RETURN: 'വാർഷിക തിരിച്ചടി',
    PER_YEAR: 'ഓരോ വർഷവും',
    FORECAST_16D: '16 ദിവസത്തെ പ്രവചനം',
    RWH_SYSTEM: 'മഴവെള്ള സംഭരണ സംവിധാനം',
    COST: 'ചെലവ്',
    CAPACITY: 'ശേഷി',
    AGR_SYSTEM: 'കൃത്രിമ ഭൂഗർഭ ജല പുനർനിറവ് സംവിധാനം',
    UTIL_VS_HARVEST: 'ഉപയോഗം vs സംഭരണ',
    ENV_IMPACT: 'പരിസ്ഥിതി സ്വാധീനം',
    WATER_SAVED: 'ജലം സംരക്ഷിച്ചു',
    GROUNDWATER_SAVED: 'ഭൂഗർഭ ജലം സംരക്ഷിച്ചു',
    ENERGY_SAVED: 'ഊർജ്ജം സംരക്ഷിച്ചു',
    CO2_AVOIDED: 'CO₂ ഒഴിവാക്കി',
    AQUIFER: 'ഭൂഗർഭ ജലസംഭരണം',
    AQUIFER_INFO: 'ജലസംഭരണ വിവരം',
    MONTHLY_FORECAST: 'മാസാന്ത്യ പ്രവചനം',
    LEADERBOARD: 'ലീഡർ ബോർഡ്',
    DRAW_HELP: 'ഒരു പോയിന്റ് ഇടാൻ ഒന്ന് ക്ലിക്ക് ചെയ്യുക, ബഹുഭുജം അടയ്ക്കാൻ ഇരട്ട ക്ലിക്ക് ചെയ്യുക',
    DRAW_ROOF: 'നിങ്ങളുടെ മേൽക്കൂരയുടെ ചുറ്റും ബഹുഭുജം വരയ്ക്കുക',
    DRAW_SPACE: 'ദയവായി ഒഴിവുള്ള സ്ഥലത്തിന്റെ ചുറ്റും ബഹുഭുജം വരയ്ക്കുക',
    ROOF_MATERIALS: 'മേൽക്കൂര സാമഗ്രികൾ',
    WATER_BILL: 'നിങ്ങളുടെ മാസാന്ത്യ ജലബിൽ എത്രയാണ്?',
    WATER_USAGE: 'മാസാന്ത്യ ഗൃഹജല ഉപഭോഗം',
    CONFIRM: 'സ്ഥിരീകരിക്കുക',
    REDO: 'വീണ്ടും ചെയ്യുക'
  },
  pa: {
    HARVEST_POTENTIAL: 'ਫਸਲ ਸੰਭਾਵਨਾ',
    SAVINGS: 'ਬਚਤ',
    ROI: 'ROI',
    PAYBACK_PERIOD: 'ਵਾਪਸੀ ਅਵਧੀ',
    YEARS: 'ਸਾਲ',
    ANNUAL_RETURN: 'ਸਲਾਨਾ ਵਾਪਸੀ',
    PER_YEAR: 'ਹਰ ਸਾਲ',
    FORECAST_16D: '16 ਦਿਨਾਂ ਦਾ ਅਨੁਮਾਨ',
    RWH_SYSTEM: 'ਮੀਹ ਦੇ ਪਾਣੀ ਦੀ ਸੰਗ੍ਰਹਿ ਪ੍ਰਣਾਲੀ',
    COST: 'ਖਰਚ',
    CAPACITY: 'ਸਮਰੱਥਾ',
    AGR_SYSTEM: 'ਕ੍ਰਿਤ੍ਰਿਮ ਭੂਜਲ ਰੀਚਾਰਜ ਪ੍ਰਣਾਲੀ',
    UTIL_VS_HARVEST: 'ਵਰਤੋਂ vs ਸੰਗ੍ਰਹਿ',
    ENV_IMPACT: 'ਪਰਿਆਵਰਣ ਪ੍ਰਭਾਵ',
    WATER_SAVED: 'ਪਾਣੀ ਬਚਾਇਆ',
    GROUNDWATER_SAVED: 'ਭੂਜਲ ਬਚਾਇਆ',
    ENERGY_SAVED: 'ਊਰਜਾ ਬਚਾਈ',
    CO2_AVOIDED: 'CO₂ ਤੋਂ ਬਚਿਆ',
    AQUIFER: 'ਭੂਜਲ ਅਕੁਇਫਰ',
    AQUIFER_INFO: 'ਅਕੁਇਫਰ ਜਾਣਕਾਰੀ',
    MONTHLY_FORECAST: 'ਮਾਸਿਕ ਅਨੁਮਾਨ',
    LEADERBOARD: 'ਲੀਡਰ ਬੋਰਡ',
    DRAW_HELP: 'ਇੱਕ ਬਿੰਦੂ ਰੱਖਣ ਲਈ ਇੱਕ ਵਾਰ ਕਲਿੱਕ ਕਰੋ, ਬਹੁਭੁਜ ਬੰਦ ਕਰਨ ਲਈ ਡਬਲ ਕਲਿੱਕ ਕਰੋ',
    DRAW_ROOF: 'ਆਪਣੀ ਛੱਤ ਦੇ ਆਲੇ ਦੁਆਲੇ ਬਹੁਭੁਜ ਬਣਾਓ',
    DRAW_SPACE: 'ਕਿਰਪਾ ਕਰਕੇ ਖਾਲੀ ਸਥਾਨ ਦੇ ਆਲੇ ਦੁਆਲੇ ਬਹੁਭੁਜ ਬਣਾਓ',
    ROOF_MATERIALS: 'ਛੱਤ ਸਮੱਗਰੀ',
    WATER_BILL: 'ਤੁਹਾਡਾ ਮਾਸਿਕ ਪਾਣੀ ਬਿੱਲ ਕਿੰਨਾ ਹੈ?',
    WATER_USAGE: 'ਮਾਸਿਕ ਘਰੇਲੂ ਪਾਣੀ ਦੀ ਵਰਤੋਂ',
    CONFIRM: 'ਪੁਸ਼ਟੀ ਕਰੋ',
    REDO: 'ਦੁਬਾਰਾ ਕਰੋ'
  },
  or: {
    HARVEST_POTENTIAL: 'ଚାଷ କ୍ଷମତା',
    SAVINGS: 'ସଞ୍ଚୟ',
    ROI: 'ROI',
    PAYBACK_PERIOD: 'ପୁଣି ଦେବା ସମୟ',
    YEARS: 'ବର୍ଷ',
    ANNUAL_RETURN: 'ବାର୍ଷିକ ଫେରତ',
    PER_YEAR: 'ପ୍ରତି ବର୍ଷ',
    FORECAST_16D: '16 ଦିନର ପୂର୍ବାନୁମାନ',
    RWH_SYSTEM: 'ବର୍ଷାଜଳ ସଞ୍ଚୟ ପ୍ରଣାଳୀ',
    COST: 'ଖର୍ଚ୍ଚ',
    CAPACITY: 'କ୍ଷମତା',
    AGR_SYSTEM: 'କୃତ୍ରିମ ଭୂଗର୍ଭ ଜଳ ପୁରଣ ପ୍ରଣାଳୀ',
    UTIL_VS_HARVEST: 'ବ୍ୟବହାର vs ସଞ୍ଚୟ',
    ENV_IMPACT: 'ପରିବେଶ ପ୍ରଭାବ',
    WATER_SAVED: 'ପାଣି ସଞ୍ଚୟ',
    GROUNDWATER_SAVED: 'ଭୂଗର୍ଭ ଜଳ ସଞ୍ଚୟ',
    ENERGY_SAVED: 'ଉର୍ଜା ସଞ୍ଚୟ',
    CO2_AVOIDED: 'CO₂ ରୋକାଗଲା',
    AQUIFER: 'ଭୂଗର୍ଭ ଜଳ ଭଣ୍ଡାର',
    AQUIFER_INFO: 'ଭଣ୍ଡାର ସୂଚନା',
    MONTHLY_FORECAST: 'ମାସିକ ପୂର୍ବାନୁମାନ',
    LEADERBOARD: 'ନେତୃତ୍ୱ ବୋର୍ଡ',
    DRAW_HELP: 'ଏକ ପଇଣ୍ଟ ରଖିବାକୁ କ୍ଲିକ୍ କରନ୍ତୁ, ପଲିଗନ ବନ୍ଦ କରିବାକୁ ଡବଲ୍ କ୍ଲିକ୍ କରନ୍ତୁ',
    DRAW_ROOF: 'ଆପଣଙ୍କ ଛାଦ ଚାରିପାଖରେ ପଲିଗନ ଅଙ୍କନ କରନ୍ତୁ',
    DRAW_SPACE: 'ଦୟାକରି ଖାଲି ସ୍ଥାନ ଚାରିପାଖରେ ପଲିଗନ ଅଙ୍କନ କରନ୍ତୁ',
    ROOF_MATERIALS: 'ଛାଦ ସାମଗ୍ରୀ',
    WATER_BILL: 'ଆପଣଙ୍କ ମାସିକ ପାଣି ବିଲ୍ କେତେ?',
    WATER_USAGE: 'ମାସିକ ଘରୋଇ ପାଣି ବ୍ୟବହାର',
    CONFIRM: 'ନିଶ୍ଚିତ କରନ୍ତୁ',
    REDO: 'ପୁଣି କରନ୍ତୁ'
  },
  ur: {
    HARVEST_POTENTIAL: 'فصل کی صلاحیت',
    SAVINGS: 'بچت',
    ROI: 'ROI',
    PAYBACK_PERIOD: 'ادائیگی کی مدت',
    YEARS: 'سال',
    ANNUAL_RETURN: 'سالانہ منافع',
    PER_YEAR: 'فی سال',
    FORECAST_16D: '16 دن کی پیشن گوئی',
    RWH_SYSTEM: 'بارش کے پانی کا ذخیرہ نظام',
    COST: 'لاگت',
    CAPACITY: 'گنجائش',
    AGR_SYSTEM: 'مصنوعی زیر زمین پانی ریچارج نظام',
    UTIL_VS_HARVEST: 'استعمال بمقابلہ قابل ذخیرہ',
    ENV_IMPACT: 'ماحولیاتی اثر',
    WATER_SAVED: 'پانی بچایا گیا',
    GROUNDWATER_SAVED: 'زیر زمین پانی بچایا گیا',
    ENERGY_SAVED: 'توانائی بچائی گئی',
    CO2_AVOIDED: 'CO₂ سے بچاؤ',
    AQUIFER: 'زیر زمین پانی کا ذخیرہ',
    AQUIFER_INFO: 'ذخیرے کی معلومات',
    MONTHLY_FORECAST: 'ماہانہ پیشن گوئی',
    LEADERBOARD: 'لیڈر بورڈ',
    DRAW_HELP: 'نقطہ رکھنے کے لیے ایک بار کلک کریں، کثیرالاضلاع بند کرنے کے لیے ڈبل کلک کریں',
    DRAW_ROOF: 'اپنی چھت کے گرد کثیرالاضلاع بنائیں',
    DRAW_SPACE: 'براہ کرم خالی جگہ کے گرد کثیرالاضلاع بنائیں',
    ROOF_MATERIALS: 'چھت کے مواد',
    WATER_BILL: 'آپ کا ماہانہ پانی کا بل کتنا ہے؟',
    WATER_USAGE: 'ماہانہ گھریلو پانی کا استعمال',
    CONFIRM: 'تصدیق کریں',
    REDO: 'دوبارہ کریں'
  }
};

  languages: Record<string, string> = {
    en: 'English',
    hi: 'हिन्दी',
    ta: 'தமிழ்',
    te: 'తెలుగు',
    bn: 'বাংলা',
    mr: 'मराठी',
    gu: 'ગુજરાતી',
    kn: 'ಕನ್ನಡ',
    ml: 'മലയാളം',
    pa: 'ਪੰਜਾਬੀ',
    or: 'ଓଡ଼ିଆ',
    ur: 'اردو'
  };


}
